# SPDX-FileCopyrightText: 2024 Thomas Breitner <mail@thms.de>
#
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-PackageName = "mkdocs-pagetree-plugin"
SPDX-PackageSupplier = "Thomas Breitner <mail@thms.de>"
SPDX-PackageDownloadLocation = "https://github.com/tombreit/mkdocs-pagetree-plugin"

[[annotations]]
path = "docs/**"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Thomas Breitner <mail@thms.de>"
SPDX-License-Identifier = "CC0-1.0"
